### ISSUE TITLE
Counting Problem.

### ISSUE THREAD

**Issue by ozgunozmumcu** [ramazan-bakir/file-word-counter#8]
When I type two space between two words, result became 3.
![57331419_1260146537475428_236488771992813568_n](https://user-images.githubusercontent.com/48850196/56443411-395aa300-62fd-11e9-951b-5e2b61519fc3.png)
![57374556_400125327233600_8964979975329415168_n](https://user-images.githubusercontent.com/48850196/56443412-3c559380-62fd-11e9-8c55-cf8d83ece5e3.png)

**Comment by RamazanBakir** [comment]
**Thank you** for noticing the problem. ### The problem has been solved in 10th commit
